### ISSUE TITLE
linux screenshot template

### ISSUE THREAD

**Issue by westofer** [Tsubajashi/mpv-settings#11]
https://github.com/Tsubajashi/mpv-settings/blob/57d7d6fab8b761ab2613419eed60cf4602a9be4f/mpv_linux.conf#L9-L12

should the the slashes be `/` and it creates a new directory?

apologizes if missuderstanding

**Comment by Tsubajashi** [comment]
yes, it should.
i actually never used the screenshot functionality in linux, but i will investigate if i made a mistake in setting things up.
if i can replicate it - ill patch it up :)

**Comment by westofer** [comment]
yes just check, linux creates directories with `/`, 

with `\` it will be a file name. should issue a pull request? or would it be more convient to patch it yourself?

**Comment by Tsubajashi** [comment]
im open to anything actually, im currently not able to use a linux machine to test it on - so if you can verify if it patches everything, you can either do a pull request, or i just change it myself, no problem

**Comment by westofer** [comment]
closing :] <3
