### ISSUE TITLE
Video sped up/audio out of sync

### ISSUE THREAD

**Issue by WonderfulSpivey** [Tsubajashi/mpv-settings#12]
When using your config without changing any settings anytime i open a video the video plays at a sped up speed and the audio is out of sync. Running Windows 10 with a GTX 1080, using the windows config. Have tested with several different file types and codecs, all with the same result.

**Comment by Tsubajashi** [comment]
thats odd, do you have the latest windows 10 and latest nvidia drivers?

**Comment by Tsubajashi** [comment]
did you also disable vsync on your desktop?

**Comment by WonderfulSpivey** [comment]
Enabling G-Sync in Nvidia Control Center has fixed the issue, I have a 244Hz monitor, is there a setting I can change in the config that won't require G-Sync to be on?

**Comment by Tsubajashi** [comment]
do you have vsync disabled in your control panel? that is the issue most probably - works fine without gsync here

**Comment by Tsubajashi** [comment]
any news to the situation? if not i would close the issue due to inactivity.

**Comment by Tsubajashi** [comment]
closed the issue due to inactivity.
