### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ghost** [Tsubajashi/mpv-settings#13]
Would be great if you included a basic list of the scripts (or maybe even the shaders) and their function and why they're used.

**Comment by Tsubajashi** [comment]
sure thing. will work on one and upload it in 1-2 days.
the scripts are more or less self explainatory, but ill do it anyway :)

**Comment by Tsubajashi** [comment]
sorry for not doing the documentation as of right now, got loads of things to do irl.

**Comment by ghost** [comment]
np
