### ISSUE TITLE
unknown keys

### ISSUE THREAD

**Issue by ghost** [Tsubajashi/mpv-settings#15]
ipc: Starting IPC master

       osc: Opened config file script-opts/osc.conf.

     stats: Opened config file script-opts/stats.conf.

       osc: script-opts/osc.conf:16 unknown key seekranges, ignoring

     stats: script-opts/stats.conf:11 unknown key plot_cache, ignoring

     stats: script-opts/stats.conf:17 unknown key blur, ignoring

     cplayer: Set property: shared-script-properties -> 1

     cplayer: Set property: shared-script-properties -> 1

no clue what this is about
why is it expecting keys?

**Comment by ghost** [comment]
osc.conf:16
![image](https://user-images.githubusercontent.com/17074394/121809552-80365000-cc5d-11eb-8366-0e9f1b86f88a.png)

stats.conf:11 & 17
![image](https://user-images.githubusercontent.com/17074394/121809577-a3f99600-cc5d-11eb-9f10-c59607e46e5a.png)

**Comment by Tsubajashi** [comment]
back when i put the settings together, it had some bonus functions. these will be excluded later on

**Comment by Tsubajashi** [comment]
the new update should patch up the issues you were having. sorry that it took me so long to get back to you. if it worked - would you kindly close the issue? :) dont want to close issues without seeing if it fixed it on your end.

**Comment by ghost** [comment]
Thanks, I can confirm the issue has been solved.
