### ISSUE TITLE
New interface doesn't work for macOS Big Sur

### ISSUE THREAD

**Issue by xiaoleichen** [Tsubajashi/mpv-settings#16]
Tested on 3 different macs. All control icons are not rendered.

(Pulled everything in repo and placed them under `~/.config/mpv/`, and renamed `mpv_osx.conf` to `mpv.conf`)
![modernx](https://user-images.githubusercontent.com/25204742/131385938-68a1d3f5-55a1-4f94-8f03-1b950e93c0fc.png)

**Comment by xiaoleichen** [comment]
Found a way around it. Replacing encoding string (`ne.content = '\xEF\x8E\xB5'`) with char itself (`ne.content = ''`) works. But any solution without changing the script would be much better.

**Comment by Tsubajashi** [comment]
you should only need to actually install the font.
that would be enough.
i tested it on macOS Monterey, so it should work with Big Sur aswell.

**Comment by WonderfulSpivey** [comment]
Can confirm interface is fine on Big Sur when included font is installed.

**Comment by Tsubajashi** [comment]
thanks for the confirmation. i will close the ticket then :)
