### ISSUE TITLE
[question] When I drag a video file into MPV, it doesn't start a 00:00:00

### ISSUE THREAD

**Issue by ghost** [Tsubajashi/mpv-settings#2]
as above.

Is it some settings in the mpv.conf? if yes, how can I change it? thank you

**Comment by Tsubajashi** [comment]
@mrjayviper can you send me a Log?

**Comment by ghost** [comment]
Not sure how to make one. Using osx version. Thank you

Edit; I'll search the net later in how to make a log

**Comment by Tsubajashi** [comment]
@mrjayviper i see, ill just try to reproduce the issue.
Did you use homebrew to install your current Installation of mpv?

**Comment by ghost** [comment]
Yes. Homebrew

**Comment by Tsubajashi** [comment]
@mrjayviper alright. I will check if i can replicate the issue and try to fix it if i can reproduce it.

**Comment by ghost** [comment]
Another question please.

What's the audio settings for?
What's the video settings before the profile? It's marked video output. How is it different from the video profiles? 

Thanks a lot

**Comment by Tsubajashi** [comment]
> Another question please.
> 
> What's the audio settings for?
> What's the video settings before the profile? It's marked video output. How is it different from the video profiles?
> 
> Thanks a lot

The Audio settings are just there for better audio quality.

the video settings before profiles are there to avoid duplication of lines, as i used a few more often.

they are inside the desired profiles, so dont worry about them!

also, i wasnt able to reproduce the issue. i will still look into it and tell you if i found something

**Comment by Tsubajashi** [comment]
i still wasnt able to repro the issue. can you provide a log what happens?
if not, am i allowed to close the issue?

**Comment by Tsubajashi** [comment]
Since you didnt respond for about 21 days, i will close the issue. if you still have that issue, reopen a new issue :)
