### ISSUE TITLE
youtube-quality.lua - does it even work anymore?

### ISSUE THREAD

**Issue by Xathros1** [Tsubajashi/mpv-settings#29]
So, I've wondered whether it was just me or if that youtube-quality.lua is actually working at all. 

Whenever I try to switch quality (ctrl-f) it always says that: "fetch formats failed" 

If it doesn't work, maybe we should just get rid of it? 

The recently introduced ytdlautoformat.lua does work, and can be configured for the wanted quality as well. (currently it defaults to 2160p; VP9 enabled; max. 60 FPS on youtube, twitch)

**Comment by Tsubajashi** [comment]
hi!
atleast on my end, it does seem to work (i didnt test the flatpak version though, this could be the culprit i think)
ill try to replicate it over the day, if it doesnt work we can get rid of it :D

**Comment by Tsubajashi** [comment]
after freshly installing another distro, it seems that it doesnt work there either. ironically, my arch install seems to work just fine with it.
I'll remove it for the time being

**Comment by Xathros1** [comment]
I did try native and flatpak. So I was wondering what's going on.
Haven't found a updated version either

9. Dez. 2022, 17:45 von ***@***.***:
