### ISSUE TITLE
Invalid value for option target-trc: Gamma2.2

### ISSUE THREAD

**Issue by Mershl** [Tsubajashi/mpv-settings#3]
Hello Tsubajashi,

My AMD Linux Setup using mpv 0.32.0 is showing:

```
Invalid value for option target-trc: Gamma2.2
Valid values are:
    auto
    bt.1886
    srgb
    linear
    gamma1.8
    gamma2.0
    gamma2.2
    gamma2.4
    gamma2.6
    gamma2.8
    prophoto
    pq
    hlg
    v-log
    s-log1
    s-log2
```
Setting the option to lowercase gamma2.2 fixes the issue.

**Comment by Tsubajashi** [comment]
Thanks for the info...
Was an oops From my side. Will update it in a day or 2 as I am not on my computer rn

**Comment by Tsubajashi** [comment]
fixed.. thanks :)
