### ISSUE TITLE
Which parameter in config increase gamma in screenshots?

### ISSUE THREAD

**Issue by BEST8OY** [Tsubajashi/mpv-settings#36]
Hello 
I have an issue with screenshots.
When I take screenshot with this repo mpv.conf parameters screenshots have higher gamma than actual playing video.
Do you know which parameter cause this?

**Comment by Tsubajashi** [comment]
Hi!
im not entirely sure if this parameter helps in your case, but screenshot-sw=yes should exactly screenshot how you see the output on your screen, as per: https://mpv.io/manual/master/#options-screenshot-sw
let me know if its the right parameter you wanted, if not, ill take another look :)

- If that doesnt work, remove line 41 and 42, this may increase consistency between screenshot and output
- if you are watching HDR videos, im not sure if that would end up looking exactly the same, i dont think vo=gpu-next or vo=gpu support that.

**Comment by BEST8OY** [comment]
![image](https://user-images.githubusercontent.com/70865987/228236567-2a493181-40ef-4b89-8e8b-451df7790a52.png)
Left is with your config intact, and right is without config.

1-I'm not watching HDR
2- I removed the whole screenshot part of config but the result was the same.
3- screenshot-sw=yes did not help.

**Comment by Tsubajashi** [comment]
now that is interesting, ill try to replicate the issue and let you know when i found something. give me 1-2 days and i probably have something for you to fix this. sorry for the trouble!
EDIT: for the time being, it may be worthwhile to remove the tonemapping settings in line 157 and 158, until i found a proper way to handle this issue

**Comment by Tsubajashi** [comment]
ok, given i dont have a windows device to test it on, i can tell you my current findings - but im still in the process to find out what really causes it:
the idea i had yesterday about the tonemapping settings does seem to affect screenshots in linux and macOS, but it still has a slight difference from no-config to my config.
so i guess its definitely one step in the right direction - just wanted to let you know that im still investigating what exactly causes those differences.

**Comment by Tsubajashi** [comment]
next status update: im now pretty sure that shaders also introduce a very slight shift in colors, depending on how they scale (luma or rgb). im not sure if i can fix it, but so far, this seems to be the next reason why there can be differences.
my recommendations then (for the time being) are disabling them if they are unneeded for the content you want to watch.

can you verify from your side if removing all tonemapping related settings change the behaviour on windows for you?

**Comment by BEST8OY** [comment]
> can you verify from your side if removing all tonemapping related settings change the behaviour on windows for you?

No
I commented tonemapping lines and screenshot were the same.
But I tried some more stuff and eventually converting gpu-next to gpu fixed it.
So, I put vo=gpu-next as the only line in the config file to see if other Parameters are involved or not but as I expected it changed the gamma in screenshots.
In the end since gpu-next has more advantages I'm gonna stick to gpu-next.
But I don't know if it's a known (bug perhaps🤷‍♂️) in mpv repo or not!

**Comment by Tsubajashi** [comment]
could very well be, i never saw this behaviour as a bug really, as it does look "better" (subjectively) in most cases.
i guess its worth it to send out an issue request to mpv directly, or libplacebo (which gpu-next heavily relies on)

**Comment by BEST8OY** [comment]
Okay
I filed an issue in mpv repo
So, I close this one.
Thanks for looking into it. 🙏

**Comment by Tsubajashi** [comment]
no problem! sorry that i wasnt able to resolve it for you.
