### ISSUE TITLE
Several notice with latest MPV

### ISSUE THREAD

**Issue by BEST8OY** [Tsubajashi/mpv-settings#38]
1- The shared-script-preparties property is deprecated and will be removed in the future. Use the user-data property instead.
It's related to the "Profiles" in config file

2- tone-mapping-mode is not supported anymore

3- ipc: Couldn't create first pipe instance: Access is denied. (0x80070005)
This one I don't know what is, so I just commented the ipc line out for myself.

4- profile is changed too 
It's okay with gpu-hq but I think it's better to use the new phrase for it "high-quality"
https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7

**Comment by Tsubajashi** [comment]
interesting changes.
IPC is for people who want to use tools like SVP for realtime video interpolation, but given it seems to error out now (?) i will also comment that out for the time being.
ill change it up soon, thanks for the notification.

**Comment by Tsubajashi** [comment]
ive now made changes based on those recommendations.
does that look fine to you?

**Comment by BEST8OY** [comment]
> ive now made changes based on those recommendations. does that look fine to you?

I think we can bring the profile section back because it doesn't seem they're causing any problem.
It seems the notice I mentioned is not related to profiles.
It's related to one of the script I use.
sorry for the misinformation.🙏

**Comment by Tsubajashi** [comment]
thats not a problem at all. i planned on getting those out of the script anyway. :)

**Comment by jakariyaa** [comment]
how did you solve it @BEST8OY  ? I presume it was related with the uosc script?
I am also using that script.

**Comment by mitch030504** [comment]
im using svp and am also getting this error
