### ISSUE TITLE
`cscale=ewa_lanczos` on my Macbook causes all video to lose saturation and have a green cast

### ISSUE THREAD

**Issue by duckpuppy** [Tsubajashi/mpv-settings#5]
The `cscale=ewa_lanczos` instruction in the `[vo]` profile causes bad colors on my Macbook Pro (2018 15"). All colors except green seem fully desaturated, and green is very muted.

I've edited the `mpv.conf` in my clone of the repo to use the `video-mac` profile, which in turn calls the `vo` profile.

**Comment by Tsubajashi** [comment]
That sounds really odd.
Do you run MPV from master, or the last stable build?

**Comment by Tsubajashi** [comment]
If you do not run it from master, we can check it with that:
https://brew.sh/
https://formulae.brew.sh/formula/mpv
mpv --HEAD
I don't have much time right now to check things up, so that might ease our way to fix it

**Comment by duckpuppy** [comment]
I do run from master via Homebrew.

And I've found a new wrinkle - while commenting out the cscale directive works on my external monitor, the desaturation is still present (without the green cast) on the Macbook screen unless I also comment out the `scale=haasnsoft` line.

**Comment by Tsubajashi** [comment]
I'll check that out soon :)

**Comment by duckpuppy** [comment]
This is a really weird issue...

**Comment by Tsubajashi** [comment]
Try to deactivate hardware decoding. that might be the issue, rather than the scaler
Haven't tested much on my mac, but that seemed to fix the issue on my end

**Comment by Tsubajashi** [comment]
did you try it again with a more recent config of mine?
just wanted to make sure, as i couldnt replicate it anymore. it seems to be fixed for me. if thats the case i would really like to close the issue, you see?

**Comment by Tsubajashi** [comment]
i'll open up the issue again, if its not fixed. you just need to comment here :)
