### ISSUE TITLE
gpu-api='d3d11' parsing error on Linux

### ISSUE THREAD

**Issue by Mershl** [Tsubajashi/mpv-settings#7]
Hi Tsubajashi,

The parsing error has no effect on functionality, just an error on the commandline when starting mpv.

Enabled profiles:
```
[default]    

# profile=video-win              # For Windows    
profile=video-linux              # For Linux
# profile=video-mac              # For Macs

profile=shaders-mixed
# profile=shader-anime
# profile=shader-liveaction
```

Error message on mpv start:
```
Error parsing option gpu-api (option parameter could not be parsed)
~/.config/mpv/mpv.conf:69: setting option gpu-api='d3d11' failed.
```

Cut-out from mpv.conf
```
L68: [d3d11]
L69: gpu-api=d3d11
L70: hwdec=no
```

**Comment by Tsubajashi** [comment]
i see... i think i can try to fix that one up in the next refresh.
if i cant get it fixed i probably split the config into 3 .confs, so the users might just choose what they want beforehand and rename it. would you like such an idea?

**Comment by ghost** [comment]
> i see... i think i can try to fix that one up in the next refresh.
> if i cant get it fixed i probably split the config into 3 .confs, so the users might just choose what they want beforehand and rename it. would you like such an idea?

this is definitely a better idea, making 3 seperate .conf files for linux windows and mac. Please do this. Also, unrelated but why is hwdec is disabled in linux?

**Comment by Mershl** [comment]
Can mpv.confs include each other? Else you would duplicate a common base.

**Comment by Tsubajashi** [comment]
#unrelated but why is hwdec is disabled in linux?
I found out that lots of people who used my config had graphical corruptions when hwdec was enabled. (Some Nvidia users for example had green screen flickering on x265 files). As soon as I think the driver situation got better on popular distros, I'll re-enable it.

**Comment by Tsubajashi** [comment]
> Can mpv.confs include each other? Else you would duplicate a common base.

Sadly I don't think it is possible, but I'll look into a similar method, if it works it'll get into the repo

**Comment by Tsubajashi** [comment]
> > i see... i think i can try to fix that one up in the next refresh.
> 
> > if i cant get it fixed i probably split the config into 3 .confs, so the users might just choose what they want beforehand and rename it. would you like such an idea?
> 
> 
> 
> this is definitely a better idea, making 3 seperate .conf files for linux windows and mac. Please do this. Also, unrelated but why is hwdec is disabled in linux?

I suppose next update will include it even when the common base is always present, so the repo will get better - I think about a method to reduce duplicates, but I don't know when that will be ready.

**Comment by Tsubajashi** [comment]
Status Report:
I didn’t have much time yet to work on this repo, but I added a To-Do List function now. Everything you might want me to change / fix / etc. Will be found there if separate issues are created.

**Comment by Tsubajashi** [comment]
did you recently check if it works alright?

**Comment by Mershl** [comment]
Hi @Tsubajashi,

The parsing error was resolved with the split of the configs. I'll create a separate issue for the errors that are now visible if you don't mind.
