### ISSUE TITLE
Invalid parameters and missing shader with mpv 0.33.

### ISSUE THREAD

**Issue by Mershl** [Tsubajashi/mpv-settings#8]
Visible errors:

```
Invalid parameter for vulkan-async-compute flag: true
Valid values are:
    yes
    no
    (passing nothing)
```

```
Invalid parameter for vulkan-async-transfer flag: true
Valid values are:
    yes
    no
    (passing nothing)
```

```
"~~/shaders/grain.glsl": No such file or directory
```

grain.glsl was removed with https://github.com/Tsubajashi/mpv-settings/commit/89021b1a0adc95a5af73d3bc86cbab1abd9037af but is referenced in .cfg

**Comment by Tsubajashi** [comment]
oops. fixing it up straight away

**Comment by Tsubajashi** [comment]
i think i fixed it up now, can you confirm?

**Comment by Mershl** [comment]
Hi @Tsubajashi, the last three commits fixed all remaining warnings on Linux I've found. Thank you very much.

**Comment by Tsubajashi** [comment]
Perfec,t no problem :)
